name: Deploy Serverless Function
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/githubconnect
          aws-region: us-east-1

      - name: Install Python and pipx
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pipx
          python3 -m pipx ensurepath
          pip install pytest

      - name: Install AWS SAM CLI
        run: |
          pipx install aws-sam-cli
          sam --version

      - name: SAM Build
        run: |
          sam build
          sam deploy \
              --stack-name lab3-test \
              --region us-east-1 \
              --capabilities CAPABILITY_IAM \
              --resolve-s3 \
              --no-confirm-changeset \
              --no-fail-on-empty-changeset
      
      - name: Create dummy image for test
        run: |
          mkdir -p tests/assets
          # This command creates a tiny valid JPEG file from a base64 string
          echo "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dnd4eXqGhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9o_ADAMBAAIRAxEAPwD7+ooooA//2Q==" | base64 -d > tests/assets/tiny.jpg

      - name: Run test
        env:
          STACK_NAME: lab3-test
        run: |
          pip install pytest boto3 Pillow
          pytest tests/test_lab3.py -v