name: Deploy Serverless Function
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/githubconnect
          aws-region: us-east-1

      - name: Install Python and pipx
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pipx
          python3 -m pipx ensurepath
          pip install pytest

      - name: Install AWS SAM CLI
        run: |
          pipx install aws-sam-cli
          sam --version

      - name: SAM Build
        run: |
          sam build
          sam deploy \
              --stack-name lab3-test \
              --region us-east-1 \
              --capabilities CAPABILITY_IAM \
              --resolve-s3 \
              --no-confirm-changeset \
              --no-fail-on-empty-changeset
      
      - name: Create local test asset
        run: |
          mkdir -p tests/assets
          # This line uses Python to "draw" a 100x100 image so the test has something to upload
          python3 -c "from PIL import Image; img = Image.new('RGB', (100, 100), color='red'); img.save('tests/assets/tiny.jpg')"

      - name: Run test
        env:
          STACK_NAME: lab3-test
        run: |
          pip install pytest boto3 Pillow
          pytest tests/test_lab3.py -v